version: "3.3"

services:
  memcached:
    image: memcached
    container_name: "memcached"
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.8
    container_name: "rabbitmq"
    env_file:
      - .env

  postgres:
    image: postgres:13.4-alpine
    restart: always
    container_name: "postgres"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}