version: "3.3"

services:
  backend:
    image: "backend-local"
    build: .
    container_name: backend
    stdin_open: true
    tty: true
    env_file:
      - .env

  celery:
    image: "backend-local"
    command: celery -A settings worker -l info --pidfile=/tmp/celery.pid
    build: .
    container_name: celery
    stdin_open: true
    tty: true
    env_file:
      - .env

  celerybeat:
    image: "beckend-local"
    command: celery -A settings beat -l info --schedule=/tmp/celerybeat-schedule --pidfile=/tmp/celerybeat.pid
    build: .
    container_name: celerybeat
    stdin_open: true
    tty: true
    env_file:
      - .env

  memcached:
    image: memcached
    container_name: "memcached"
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.9.5-management-alpine
    container_name: "rabbitmq"
    env_file:
      - .env

  nginx:
    image: nginx:1.19
    container_name: "nginx"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:8080"  # windows specific!!!
      #- "80:80"
      #- "443:443"

  flower:
    image: mher/flower
    container_name: flower
    #    command: celery --broker=amqp://guest:guest@rabbitmq:5672// flower
    command: celery --broker=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${RABBITMQ_DEFAULT_HOST}:${RABBITMQ_DEFAULT_PORT}// flower
    depends_on:
      - rabbitmq

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./portainer:/data"
    restart: always # unless-stopped