# Generated by Django 3.2.3 on 2021-05-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='source',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
