# Generated by Django 3.2.3 on 2021-08-24 20:48

from django.db import migrations


def forwards(apps, schema_editor):
    Rate = apps.get_model('currency', 'Rate')
    Bank = apps.get_model('currency', 'Bank')

    privatbank = Bank.objects.create(
        name='PrivatBank',
        url='https://api.privatbank.ua/p24api/pubinfo?json&exchange&coursid=5',
        original_url='https://privatbank.ua/',
    )
    monobank = Bank.objects.create(
        name='MonoBank',
        url='https://api.monobank.ua/bank/currency',
        original_url='https://www.monobank.ua/',
    )
    vkurse = Bank.objects.create(
        name='Vkurse',
        url='http://vkurse.dp.ua/course.json',
        original_url='http://vkurse.dp.ua',
    )
    iboxbank = Bank.objects.create(
        name='IboxBank',
        url='https://app.iboxbank.online/api/currency/rate-only-base/UAH',
        original_url='https://iboxbank.online/',
    )
    alfabank = Bank.objects.create(
        name='AlfaBank',
        url='https://alfabank.ua/',
        original_url='https://alfabank.ua/',
    )
    oschadbank = Bank.objects.create(
        name='OschadBank',
        url='https://www.oschadbank.ua/',
        original_url='https://www.oschadbank.ua/',
    )

    for rate in Rate.objects.all():
        if 'privatbank' in rate.source.lower():
            rate.bank = privatbank
        if 'monobank' in rate.source.lower():
            rate.bank = monobank
        if 'vkurse' in rate.source.lower():
            rate.bank = vkurse
        if 'iboxbank' in rate.source.lower():
            rate.bank = iboxbank
        if 'alfabank' in rate.source.lower():
            rate.bank = alfabank
        if 'oschadbank' in rate.source.lower():
            rate.bank = oschadbank

        rate.save()


def backwards(apps, schema_editor):
    # Post = apps.get_model('blog', 'Post')
    print('HELLO FROM BACKWARDS!')  # noqa


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20210824_2344'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
