# Generated by Django 3.2.3 on 2021-09-03 13:42

import currency.models

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_alter_bank_code_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_logo',
            field=models.FileField(blank=True, default=None, null=True, upload_to=currency.models.bank_directory_path),
        ),
        migrations.AlterField(
            model_name='bank',
            name='code_name',
            field=models.CharField(default=None, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
