# Generated by Django 3.2.3 on 2021-05-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_rate_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.EmailField(max_length=64)),
                ('subject', models.CharField(max_length=5)),
                ('message', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='rate',
            name='type',
        ),
        migrations.AddField(
            model_name='rate',
            name='type1',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
