# Generated by Django 3.2.3 on 2021-09-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20210903_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='request_method',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, 'GET'),
                    (1, 'POST'),
                    (2, 'PUT'),
                    (3, 'PATCH'),
                    (4, 'DELETE'),
                ]
            ),
        ),
    ]
