# Generated by Django 3.2.3 on 2021-06-07 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20210531_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='type1',
            new_name='type',
        ),
    ]
