# Generated by Django 3.2.3 on 2021-08-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0007_auto_20210623_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='type',
            field=models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro')], max_length=5),
        ),
    ]
