# Generated by Django 3.2.3 on 2021-08-06 19:51

from django.db import migrations
# from currency.models import Rate WRONG


def forwards(apps, schema_editor):
    Rate = apps.get_model('currency', 'Rate')
    for rate in Rate.objects.all():
        rate.type_new = 1 if 'eur' in rate.type.lower() else 0
        rate.save()


def backwards(apps, schema_editor):
    # Post = apps.get_model('blog', 'Post')
    print('HELLO FROM BACKWARDS!')  # noqa


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_auto_20210806_2247'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
