# Generated by Django 3.2.3 on 2021-08-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0010_auto_20210806_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='type',
        ),
    ]
