# Generated by Django 3.2.3 on 2021-08-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_remove_rate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='type_new',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Dollar'), (1, 'Euro')]),
        ),
    ]
