# Generated by Django 3.2.3 on 2021-08-08 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0014_analytics'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analytics',
            unique_together={('path', 'request_method')},
        ),
    ]
