# Generated by Django 3.2.3 on 2021-08-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0015_alter_analytics_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='status_code',
            field=models.CharField(default='default status', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='analytics',
            unique_together={('path', 'request_method', 'status_code')},
        ),
    ]
