# Generated by Django 3.2.3 on 2021-08-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0019_alter_rate_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='code_name',
            field=models.CharField(default=None, null=True, max_length=255, unique=True),
        ),
    ]
