# Generated by Django 3.2.3 on 2021-08-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0020_bank_code_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='source',
        ),
    ]
